# Change these first
owner: merge1973
repo: skyfallmc-server-status

sites:
  - name: Main Website
    url: https://play.skyfallmc.ga
    maxResponseTime: 5000
  - name: Files Website
    url: https://files.skyfallmc.ga
    maxResponseTime: 5000
  - name: SkyfallSMP Map
    url: https://map.skyfallmc.ga
    maxResponseTime: 5000
  - name: Server Statistics
    url: https://stats.skyfallmc.ga
    maxResponseTime: 5000
  - name: SkyfallMC Minecraft Server
    check: "tcp-ping"
    url: play.skyfallmc.ga
    port: 25565
    maxResponseTime: 5000
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.skyfallmc.ga
  # baseUrl: /your-repo-name
  logoUrl: https://play.skyfallmc.ga/assets/logo.png
  theme: night
  name: SkyfallMC Status Page
  introTitle: "Welcome to the SkyfallMC Status Page"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Home
      href: https://play.skyfallmc.ga
workflowSchedule:
  graphs: "0 */4 * * *"
  responseTime: "0 */4 * * *"
  staticSite: "0 0 * * 0"
  summary: "0 */4 * * *"
  updateTemplate: "0 0 * * 0"
  updates: "0 0 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
