# Change these first
owner: merge1973
repo: skyfallmc-server-status

sites:
  - name: Main Website
    url: https://play.skyfallmc.cc
    maxResponseTime: 1000
    icon: https://play.skyfallmc.cc/assets/favicon-32x32.svg
  - name: Files Website
    url: https://files.skyfallmc.cc
    maxResponseTime: 1000
    icon: https://play.skyfallmc.cc/assets/favicon-32x32.svg
  - name: SkyfallSMP Map
    url: https://map.skyfallmc.cc
    maxResponseTime: 1000
    icon: https://map.skyfallmc.cc/live-atlas/favicons/favicon.svg   
  - name: Server Statistics
    url: https://stats.skyfallmc.cc
    maxResponseTime: 1000
    icon: https://play.skyfallmc.cc/assets/favicon-32x32.svg
  - name: SkyfallMC Minecraft Server
    check: "tcp-ping"
    url: play.skyfallmc.cc
    port: 25565
    maxResponseTime: 1000
    icon: https://play.skyfallmc.cc/assets/favicon-32x32.svg
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.skyfallmc.cc
  # baseUrl: /your-repo-name
  logoUrl: https://play.skyfallmc.cc/assets/statuslogo.svg
  theme: night
  name: SkyfallMC Status Page
  introTitle: "Welcome to the SkyfallMC Status Page"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Home
      href: https://play.skyfallmc.cc
# Looks like Upptime is broken, pause checking for uptime and response time    
workflowSchedule:
  graphs: "0 */4 * * *"
  responseTime: "0 */4 * * *"
  staticSite: "0 0 * * 0"
  summary: "0 */4 * * *"
  updateTemplate: "0 0 * * 0"
  updates: "0 0 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
